/** UI dependencies: $, badge, branchHint, empty, esc, field, inventoryQuery, inventoryStock, kind, kinds, list, model, money, productOptions, selectedAudit, specific, table, uiDialogButton. Injected by app composition. */
export function createInventoryViews(ctx) {
function filterInventory(){const q=ctx.inventoryQuery.toLocaleLowerCase('es');let visible=0;document.querySelectorAll('[data-inventory-row]').forEach(row=>{row.hidden=!row.dataset.search.includes(q)||(ctx.inventoryStock==='low'&&Number(row.dataset.stock)>0);if(!row.hidden)visible++;});if(ctx.$('#inventoryMatch'))ctx.$('#inventoryMatch').textContent=`${visible} productos en la lista`;if(ctx.$('#inventoryNoMatch'))ctx.$('#inventoryNoMatch').hidden=visible>0;}
function auditFilter(){const pending=ctx.$('#auditPending')?.checked;document.querySelectorAll('.count').forEach(input=>input.closest('tr').hidden=!!pending&&input.value!=='');}
function inventory(){
 if(!candyAuditVisible())return '<div class="banner">El inventario solo está disponible durante un arqueo activo.</div>';
 if(ctx.model.user.role==='administrator')ctx.kind='vault';if(ctx.model.user.role==='candy')ctx.kind='candy';
 const products=ctx.list('products').filter(p=>p.kind===ctx.kind),locked=ctx.list('audits').some(a=>a.kind===ctx.kind&&a.status==='En curso');
 const options=['manager','accounting'].includes(ctx.model.user.role)?`<div class="tabs"><button data-kind="candy" class="${ctx.kind==='candy'?'active':''}">Candy bar</button><button data-kind="vault" class="${ctx.kind==='vault'?'active':''}">Bóveda de Administración</button></div>`:'';
 let actions='';if(ctx.model.user.role==='accounting'&&ctx.specific()){actions=ctx.uiDialogButton('newProduct','Registrar producto',`<p class="muted">El código se asigna automáticamente. Después de crear el producto registra su entrada.</p><form data-action="product" class="form-grid">${ctx.field('Producto','name')}${ctx.field('Unidad','unit','text','Unidad')}${ctx.field(ctx.kind==='candy'?'Precio de venta · BOB':'Costo unitario · BOB','price','number','','min="0.01" step="0.01"')}<button class="primary" ${locked?'disabled':''}>Crear producto</button></form>`,'＋ Nuevo producto',true);if(ctx.kind==='candy')actions+=ctx.uiDialogButton('newStock','Registrar entrada o salida',movementForm('stock',locked),'Registrar movimiento');}
 if(ctx.model.user.role==='administrator')actions+=ctx.uiDialogButton('newVaultReport','Reportar entrada o salida',`<p class="muted">Contabilidad validará el movimiento antes de actualizar las existencias.</p>${movementForm('report',locked)}`,'＋ Reportar movimiento',true);
 return options+`${locked?'<div class="banner warning">Arqueo en curso · Las existencias se actualizarán al validar el conteo.</div>':''}<section class="panel"><div class="panel-head"><div><p class="eyebrow">EXISTENCIAS OFICIALES</p><h2>${ctx.kinds[ctx.kind]}</h2></div><div class="inline-actions">${actions}</div></div><div class="list-filters"><label>Buscar producto<input id="inventorySearch" type="search" placeholder="Nombre o código…" value="${ctx.esc(ctx.inventoryQuery)}"></label><label>Existencias<select id="inventoryStock"><option value="all">Todos los productos</option><option value="low" ${ctx.inventoryStock==='low'?'selected':''}>En cero o negativas</option></select></label><small id="inventoryMatch">${products.length} productos en la lista</small></div>${ctx.table(['Producto','Existencia','Unidad',ctx.kind==='candy'?'Precio de venta':'Costo unitario'],products.map(product=>`<tr data-inventory-row data-search="${ctx.esc((product.name+' '+product.code).toLocaleLowerCase('es'))}" data-stock="${product.stock}"><td><strong>${ctx.esc(product.name)}</strong><small>${ctx.esc(product.code)}</small></td><td class="${product.stock<=0?'negative':'stock-number'}">${product.stock}</td><td>${ctx.esc(product.unit)}</td><td>${ctx.money(product.price)}</td></tr>`))}<p id="inventoryNoMatch" class="empty" hidden>No hay productos con esos filtros.</p></section>${ctx.kind==='vault'&&ctx.model.user.role==='accounting'?'<div class="banner">Las entradas y salidas de bóveda se aprueban desde <button data-page="reports">Reportes de movimientos →</button></div>':''}`;
}
function movementForm(action,locked=false){return `<form data-action="${action}" class="form-grid"><label>Producto<select name="item" required>${ctx.productOptions()}</select></label><label>Movimiento<select name="direction"><option value="in">Entrada</option><option value="out">Salida</option></select></label>${ctx.field('Cantidad','quantity','number',1,'min="1"')}${ctx.field('Motivo / respaldo','reason')}<button class="primary" ${locked?'disabled':''}>${action==='report'?'Enviar a validación':'Registrar movimiento'} →</button></form>`;}
function reports(){
 let form='';if(ctx.model.user.role==='administrator'){ctx.kind='vault';form=`<section class="panel"><div class="panel-head"><div><h2>Reportar movimientos</h2><small>Contabilidad valida cada entrada o salida antes de actualizar las existencias.</small></div>${ctx.uiDialogButton("reportMovement","Reportar entrada o salida",movementForm("report",ctx.list("audits").some(a=>a.kind==="vault"&&a.status==="En curso")),"＋ Nuevo reporte",true)}</div></section>`;}
 return (ctx.candyRequests())+form+`<section class="panel"><div class="panel-head"><h2>Movimientos y validaciones</h2><label class="search-field">Buscar reporte<input type="search" data-filter-table="movementRecords" placeholder="Producto, estado o usuario…"></label></div><div id="movementRecords">${ctx.table(['Fecha / usuario','Producto','Sucursal','Unidades','Motivo','Estado / revisión'],ctx.list('reports').slice().reverse().map(r=>`<tr><td>${r.at.slice(0,16).replace('T',' ')}<small>${r.user}</small></td><td>${ctx.esc(r.name)}</td><td>${r.branch}</td><td class="${r.delta<0?'negative':'amount'}">${r.delta>0?'+':''}${r.delta}</td><td>${ctx.esc(r.reason)}${r.note?`<small>Revisión: ${ctx.esc(r.note)}</small>`:''}</td><td>${ctx.badge(r.status)}${ctx.model.user.role==='accounting'&&['Pendiente','Observado'].includes(r.status)?`<form data-action="review" data-id="${r.id}" data-branch="${r.branch}" class="compact"><select name="status"><option>Aprobado</option><option>Observado</option><option>Rechazado</option></select><input name="note" placeholder="Motivo de revisión" required><button>Guardar revisión</button></form>`:''}</td></tr>`))}</div></section>`;
}
function audits(){
 const items=ctx.list('audits'),audit=items.find(a=>a.id===ctx.selectedAudit)||items.find(a=>a.status==='En curso')||items.at(-1);ctx.selectedAudit=audit?.id||'';const can=ctx.model.user.role==='accounting';
 let body='<div class="banner">Candy se valora al precio de venta; bóveda, al costo unitario. Se incluyen existencias cero y negativas.</div>';
 if(can)body+=`<section class="panel"><h2>Iniciar conteo y bloquear operación</h2>${ctx.specific()?`<form data-action="audit_start" class="inline-form"><label>Inventario<select name="kind"><option value="candy">Candy bar · bloquear ventas</option><option value="vault">Bóveda · bloquear movimientos</option></select></label><button class="primary">Iniciar arqueo + PDF →</button></form><p class="muted small">Resuelve los reportes pendientes antes de iniciar. El PDF también estará disponible para descargar nuevamente.</p>`:ctx.branchHint()}</section>`;
 body+=`<section class="panel"><div class="panel-head"><h2>Arqueos y conteos</h2><select id="auditSelect" aria-label="Seleccionar arqueo"><option value="">Seleccionar arqueo</option>${items.slice().reverse().map(a=>`<option value="${a.id}" ${a.id===ctx.selectedAudit?'selected':''}>${a.branch} / ${ctx.kinds[a.kind]} / ${a.at.slice(0,16)} / ${a.status}</option>`).join('')}</select></div>`;
 if(!audit)return body+ctx.empty('Sin arqueos registrados')+'</section>';const editable=can&&audit.status==='En curso';
 body+=`<div class="panel-head"><div>${ctx.badge(audit.status)} <span class="muted">N.º ${audit.id} · ${audit.branch} · ${ctx.kinds[audit.kind]}</span></div><a class="button" href="/api/pdf/${audit.id}">↓ Hoja de conteo PDF</a></div><div class="audit-progress"><div><strong id="auditProgressText">Preparando conteo</strong><progress id="auditProgress" value="0" max="1" aria-label="Avance del conteo"></progress></div><label class="check-label"><input type="checkbox" id="auditPending"> Solo pendientes</label></div><form data-action="audit_save" data-id="${audit.id}" data-branch="${audit.branch}">${ctx.table(['Producto','Sistema','Valor unitario','Conteo físico','Diferencia','Sobrante / faltante BOB'],audit.rows.map(r=>`<tr><td><strong>${ctx.esc(r.name)}</strong><small>${ctx.esc(r.unit)}</small></td><td>${r.system}</td><td>${ctx.money(r.price)}</td><td><input class="count" name="${r.item}" data-system="${r.system}" data-price="${r.price}" type="number" min="0" step="1" value="${r.physical??''}" ${editable?'':'disabled'} aria-label="Conteo físico de ${ctx.esc(r.name)}"></td><td class="difference"></td><td class="valuation"></td></tr>`))}<div id="auditTotals" class="audit-totals"></div>${editable?'<div class="actions"><button>Guardar avance</button><button class="primary" name="finish" value="yes">Verificar y finalizar arqueo →</button></div><p class="muted small">Finalizar reemplaza las existencias oficiales por el conteo físico y desbloquea la operación. Esta acción queda en el historial.</p>':''}</form></section>`;return body;
}
function candyAuditVisible(){return ctx.model?.user.role!=='candy'||ctx.list('audits').some(a=>a.kind==='candy'&&a.status==='En curso');}
function calculate(){let plus=0,minus=0,pending=0;document.querySelectorAll('.count').forEach(input=>{const filled=input.value!=='';const d=filled?Number(input.value)-Number(input.dataset.system):0,v=d*Number(input.dataset.price),row=input.closest('tr');row.querySelector('.difference').textContent=filled?(d>0?'+':'')+d:'Pendiente';row.querySelector('.valuation').textContent=filled?ctx.money(v):'—';row.querySelector('.valuation').className='valuation '+(v<0?'negative':'amount');if(!filled)pending++;plus+=Math.max(0,v);minus+=Math.max(0,-v);});const counts=document.querySelectorAll('.count');if(ctx.$('#auditProgress')){ctx.$('#auditProgress').max=counts.length||1;ctx.$('#auditProgress').value=counts.length-pending;ctx.$('#auditProgressText').textContent=`${counts.length-pending} de ${counts.length} productos contados`;}if(ctx.$('#auditTotals'))ctx.$('#auditTotals').innerHTML=`<span>Sobrantes <strong>${ctx.money(plus)}</strong></span><span>Faltantes <strong class="negative">${ctx.money(minus)}</strong></span><span>Pendientes <strong>${pending}</strong></span>`;}
return {inventory,reports,audits,calculate,filterInventory,auditFilter,candyAuditVisible};
}
