import { restorePendingTicket, submitTicketSale } from './application.ts';
/** UI dependencies: $, api, branch, cashClosed, esc, list, model, money, notify, page, refresh, refreshView, table. Local basket state stays inside this factory. */
export function createTicketingController(ctx) {
let controller;
let cart=[],date='',query='',receipt=null,pending=null,working=false,owner='',chosen={};
const key=()=> 'ticket-checkout-'+ctx.model.user.id;
const freshId=()=>crypto.randomUUID();
const shows=()=>ctx.list('shows').filter(s=>!s.cancelled&&s.date+'T'+s.time>=ctx.model.serverTime).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));
const closed=()=>ctx.cashClosed();
const total=()=>cart.reduce((sum,r)=>sum+Math.round(r.unitPrice*100)*r.quantity,0)/100;
function remember(){try{if(pending)sessionStorage.setItem(key(),JSON.stringify(pending));else sessionStorage.removeItem(key());}catch{}}
function ensure(){if(owner!==ctx.model.user.id){owner=ctx.model.user.id;cart=[];receipt=null;date='';pending=null;try{pending=restorePendingTicket(sessionStorage.getItem(key()));if(pending)cart=pending.lines;}catch{pending=null;}}if(!date)date=shows().find(s=>s.date>=ctx.model.today)?.date||ctx.model.today;}
function current(r){return ctx.list('shows').find(s=>s.id===r.item);}
function cartHTML(){const unavailable=cart.some(r=>{const s=current(r);return !s||s.cancelled||s.date<ctx.model.today||s.date+'T'+s.time<ctx.model.serverTime||r.quantity>ctx.model.state.availability[r.item];});return `<div class="panel-head"><div><p class="eyebrow">TU VENTA</p><h2>Boletos seleccionados</h2></div><span class="badge">${cart.reduce((n,r)=>n+r.quantity,0)} boletos</span></div>${pending?'<div class="banner warning">Hay una confirmación pendiente. Reintenta para recuperar el resultado sin duplicar la venta.</div>':''}${cart.map(r=>{const s=current(r),left=ctx.model.state.availability[r.item]||0;return `<article class="cart-line"><strong>${ctx.esc(s?.title||r.title||'Función no disponible')}</strong><small>${ctx.esc(s?.date||r.date)} · ${ctx.esc(s?.time||r.time)} · ${ctx.esc(s?.room||r.room)}</small><div class="cart-controls"><button data-ticket-minus="${r.item}" ${pending?'disabled':''} aria-label="Restar boleto de ${ctx.esc(s?.title)}">−</button><input type="number" min="1" max="2000" value="${r.quantity}" data-ticket-qty="${r.item}" aria-label="Cantidad para ${ctx.esc(s?.title)}" ${pending?'disabled':''}><button data-ticket-plus="${r.item}" ${pending?'disabled':''} aria-label="Sumar boleto de ${ctx.esc(s?.title)}">+</button><b>${ctx.money(r.unitPrice*r.quantity)}</b><button data-ticket-remove="${r.item}" ${pending?'disabled':''} aria-label="Quitar ${ctx.esc(s?.title)}">×</button></div><small>${ctx.money(r.unitPrice)} por boleto · ${r.seatsPerTicket===2?'2×1 · ':''}${r.quantity*r.seatsPerTicket} butacas</small>${!s||s.cancelled||r.quantity>left?`<p class="negative">Disponibilidad actual: ${left}. Ajusta o retira esta función.</p>`:''}</article>`;}).join('')||'<div class="empty cart-empty"><span class="empty-icon" aria-hidden="true">＋</span><h3>Tu venta empieza aquí</h3><p>Elige una película, un horario y la cantidad de boletos.</p></div>'}<div class="checkout-total"><span>Total a cobrar</span><strong>${ctx.money(total())}</strong></div><label>Importe recibido (opcional)<input id="ticketReceived" type="number" min="0" step="0.01" placeholder="BOB" ${pending?'disabled':''} value="${pending?.received??''}"></label><p id="ticketChange" class="muted">Sin registro de medio de pago.</p><button id="ticketFinish" class="primary" ${working||(!pending&&(closed()||!cart.length||unavailable))?'disabled':''}>${working?'Confirmando…':pending?'Reintentar confirmación':'Finalizar venta →'}</button>${cart.length&&!pending?'<button id="ticketClear" class="subtle">Vaciar lista</button>':''}<p class="muted small">Los boletos se descuentan al finalizar, no al agregarlos a la lista.</p>`;}
function prettyDate(value){return new Date(value+'T12:00:00').toLocaleDateString('es-BO',{weekday:'short',day:'numeric',month:'short'});}
function progressHTML(){return window.UniversalUI.steps(['Función','Boletos','Confirmación'],receipt?2:cart.length?1:0);}
function dockHTML(){const count=cart.reduce((n,r)=>n+r.quantity,0);return `<div class="pos-mobile-dock" id="ticketDock"><div><small>${count} boletos en tu venta</small><strong>${ctx.money(total())}</strong></div><button class="primary" data-ticket-cart="yes">Ver venta <span aria-hidden="true">↑</span></button></div>`;}
function gridHTML(){
 const items=shows().filter(s=>s.date===date&&s.title.toLocaleLowerCase().includes(query.toLocaleLowerCase())),groups=new Map();
 for(const s of items){const id=s.movieId||s.title;if(!groups.has(id))groups.set(id,[]);groups.get(id).push(s);}
 return [...groups].map(([id,functions])=>{const selected=functions.find(s=>s.id===chosen[id]),movie=ctx.list('movies').find(m=>m.id===functions[0].movieId),poster=movie?.poster;return `<article class="ticket-show ticket-movie ${selected?'has-selection':''}"><div class="ticket-movie-heading">${poster?`<img class="ticket-poster" src="${ctx.esc(poster)}" alt="" loading="lazy" referrerpolicy="no-referrer">`:'<span class="ticket-poster ticket-poster-empty" aria-hidden="true">▸</span>'}<div><p class="eyebrow">${functions.length} ${functions.length===1?'HORARIO':'HORARIOS'} · ${ctx.esc(prettyDate(date))}</p><h2>${ctx.esc(functions[0].title)}</h2>${movie?`<p class="ticket-movie-meta">${ctx.esc([movie.genre,movie.duration?movie.duration+' min':'',movie.rating].filter(Boolean).join(' · '))}</p>`:''}</div></div><div class="ticket-times" aria-label="Horarios de ${ctx.esc(functions[0].title)}">${functions.map(s=>`<button type="button" data-ticket-time="${s.id}" aria-pressed="${selected?.id===s.id}" class="${selected?.id===s.id?'active':''} ${!ctx.model.state.availability[s.id]?'is-soldout':''}"><strong>${s.time}</strong><small>${ctx.esc(s.format)}${functions.filter(f=>f.time===s.time).length>1?' · '+ctx.esc(s.room):''}${!ctx.model.state.availability[s.id]?' · Agotada':''}</small></button>`).join('')}</div>${selected?showDetails(selected):'<p class="ticket-prompt"><span aria-hidden="true">↳</span> Elige un horario para ver la sala, el precio y los boletos disponibles.</p>'}</article>`;}).join('')||`<div class="panel empty"><span class="empty-icon" aria-hidden="true">▸</span><h3>No encontramos funciones</h3><p>Prueba otra película o fecha. La programación depende de esta sucursal.</p></div>`;
}
function showDetails(s){const inCart=cart.find(r=>r.item===s.id)?.quantity||0,left=ctx.model.state.availability[s.id]||0;return `<section class="ticket-details" aria-label="Detalle de ${ctx.esc(s.title)} a las ${s.time}"><div class="panel-head"><strong>${ctx.esc(s.room)} · ${s.format}</strong>${s.seatsPerTicket===2?'<span class="badge good">2×1</span>':''}</div><div class="ticket-facts"><div><small>Precio por boleto</small><strong>${ctx.money(s.price)}</strong></div><div><small>Boletos disponibles</small><strong>${left}</strong></div></div><p class="muted small">${s.capacity} butacas en sala${s.seatsPerTicket===2?' · Cada boleto ocupa 2 butacas':''}${inCart?' · '+inCart+' boletos en tu lista':''}</p><div class="ticket-add"><label>Cantidad<input type="number" min="1" max="${Math.max(1,left-inCart)}" value="1" data-ticket-addqty="${s.id}" aria-label="Boletos de ${ctx.esc(s.title)} a las ${s.time}"></label><button data-ticket-add="${s.id}" ${closed()||pending||left<=inCart?'disabled':''}>${left?'Agregar a la venta +':'Agotada'}</button></div></section>`;}
function printStatus(o){const p=o.printing,waiting=['pending','sending'].includes(p?.status),repeat=['queued','uncertain'].includes(p?.status);return `<p class="${['pending','sending','queued','manual'].includes(p?.status)?'muted':'negative'}">${ctx.esc(p?.message||'Impresión pendiente.')}</p>${p?.status==='manual'?'':`<button data-print-order="${o.id}" data-print-repeat="${repeat}" ${waiting?'disabled':''}>${waiting?'Esperando impresión…':repeat?'Reimprimir entradas':'Enviar a la Epson'}</button>`}`;}
function receiptHTML(){return receipt?`<section class="panel ticket-success"><p class="eyebrow">VENTA FINALIZADA</p><h2>${ctx.money(receipt.total)} · ${receipt.lines.reduce((n,r)=>n+r.quantity,0)} boletos</h2><p>Comprobante ${ctx.esc(receipt.id)}${receipt.change!==null?' · Cambio: '+ctx.money(receipt.change):''}</p><a class="button primary" href="/api/receipt/${receipt.id}" target="_blank" rel="noopener">Ver entradas individuales ↗</a>${printStatus(receipt)}<button id="ticketNew">Nueva venta</button></section>`:'';}
function render(){ensure();if(receipt){receipt=(ctx.model.state.orders||[]).find(order=>order.id===receipt.id)||receipt;}const dates=[...new Set([ctx.model.today,...shows().map(s=>s.date)])];return `${closed()?'<div class="banner warning">Tu caja de hoy está cerrada. Puedes consultar y reimprimir tus ventas.</div>':''}${!shows().some(s=>s.date===ctx.model.today)?'<div class="banner">No hay funciones programadas para hoy. Puedes vender anticipadamente las próximas funciones.</div>':''}${receiptHTML()}<div id="ticketProgress">${progressHTML()}</div><div class="pos-section-heading"><div><h2>Elige la película y el horario</h2><p class="muted">${ctx.esc(ctx.branch)} · Boletos para hoy y próximas funciones</p></div><a class="button subtle-inline" href="#ticketReceipts">Mis comprobantes ↓</a></div><div class="ticket-layout"><section><div class="panel ticket-filters"><label>Fecha de la función<select id="ticketDate">${dates.map(d=>`<option value="${d}" ${d===date?'selected':''}>${ctx.esc(prettyDate(d))}${d===ctx.model.today?' · Hoy':''}</option>`).join('')}</select></label><label>Buscar película<input id="ticketSearch" type="search" value="${ctx.esc(query)}" placeholder="Busca por título" autocomplete="off"></label></div><div id="ticketGrid" class="ticket-grid">${gridHTML()}</div></section><section id="ticketCart" class="panel ticket-cart" tabindex="-1" aria-label="Resumen de venta">${cartHTML()}</section></div>${dockHTML()}<section class="panel pos-receipts" id="ticketReceipts"><div class="panel-head"><div><p class="eyebrow">VENTAS REGISTRADAS</p><h2>Mis comprobantes</h2></div></div>${ctx.table(['Fecha de venta','Comprobante','Boletos','Total','Impresión'],(ctx.model.state.orders||[]).slice().reverse().map(o=>`<tr><td>${o.at.slice(0,16).replace('T',' ')}</td><td>${ctx.esc(o.id)}</td><td>${o.lines.reduce((n,r)=>n+r.quantity,0)}</td><td>${ctx.money(o.total)}</td><td><a class="button" href="/api/receipt/${o.id}" target="_blank" rel="noopener">Ver entradas ↗</a>${printStatus(o)}</td></tr>`))}</section>`;}
function updateCart(){const received=ctx.$('#ticketReceived')?.value;ctx.$('#ticketCart').innerHTML=cartHTML();if(!pending&&received!==undefined)ctx.$('#ticketReceived').value=received;change();live();updateDock();}
function updateDock(){if(ctx.$('#ticketProgress'))ctx.$('#ticketProgress').innerHTML=progressHTML();const dock=ctx.$('#ticketDock');if(dock)dock.outerHTML=dockHTML();}
function change(){if(!ctx.$('#ticketChange'))return;const received=ctx.$('#ticketReceived').value;ctx.$('#ticketChange').textContent=received===''?'Sin registro de medio de pago.':Number(received)>=total()?'Cambio: '+ctx.money(Number(received)-total()):'Falta cobrar: '+ctx.money(total()-Number(received));}
function live(){if(!ctx.$('#ticketGrid'))return;updateDock();if(!ctx.$('#ticketGrid').contains(document.activeElement))ctx.$('#ticketGrid').innerHTML=gridHTML();const cartPanel=ctx.$('#ticketCart');if(cartPanel&&!cartPanel.contains(document.activeElement)&&!working){const received=ctx.$('#ticketReceived')?.value;cartPanel.innerHTML=cartHTML();if(!pending&&received!==undefined)ctx.$('#ticketReceived').value=received;change();}const button=ctx.$('#ticketFinish');if(button&&!pending)button.disabled=working||closed()||!cart.length||cart.some(r=>!current(r)||current(r).cancelled||current(r).date+'T'+current(r).time<ctx.model.serverTime||r.quantity>(ctx.model.state.availability[r.item]||0));}
async function finish(){if(working)return;if(!pending){if(!cart.length||closed())return;const received=ctx.$('#ticketReceived').value;if(received!==''&&(!Number.isFinite(Number(received))||Number(received)<total()))return ctx.notify('El importe recibido no alcanza el total.');pending={action:'ticket_checkout',branch:ctx.model.user.branch,requestId:freshId(),lines:cart.map(r=>({...r})),received};remember();}working=true;updateCart();try{const response=await submitTicketSale(ctx.transport,pending);const result=response.body;if(!response.ok){if(response.status>=500||response.status===429)throw new Error('Confirmación pendiente');pending=null;remember();await ctx.refresh(true);cart=cart.map(r=>{const s=current(r);return s?{...r,unitPrice:s.price,seatsPerTicket:s.seatsPerTicket}:r;});ctx.notify(result.error||'No se pudo confirmar. Revisa la lista.');return;}receipt=result.order;cart=[];pending=null;remember();await ctx.refresh(true);ctx.notify(result.repeated?'Comprobante recuperado. La venta no se duplicó.':'Venta finalizada. '+(receipt.printing?.message||'Revisa el estado de impresión.'));}catch{ctx.notify('No se recibió la confirmación. Reintenta para comprobar la misma venta sin duplicarla.');}finally{working=false;ctx.refreshView();}}
controller={render,live,reset(){chosen={};owner='';cart=[];date='';query='';receipt=null;pending=null;}};
ctx.$('#root').addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||ctx.model?.user.role!=='ticketing')return;if(b.dataset.ticketCart){ctx.$('#ticketCart')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});ctx.$('#ticketCart')?.focus({preventScroll:true});return;}if(b.dataset.printOrder){if(working)return;const repeat=b.dataset.printRepeat==='true';if(repeat&&!confirm('Revisa si los boletos ya salieron. ¿Enviar otra copia de todas las entradas?'))return;working=true;b.disabled=true;const requestKey='ticket-print-'+ctx.model.user.id+'-'+b.dataset.printOrder;let requestId;try{requestId=sessionStorage.getItem(requestKey)||freshId();sessionStorage.setItem(requestKey,requestId);}catch{requestId=b.dataset.printRequest||freshId();}b.dataset.printRequest=requestId;try{const result=await ctx.api('print',{order:b.dataset.printOrder,reprint:repeat,requestId});try{sessionStorage.removeItem(requestKey);}catch{}if(receipt?.id===b.dataset.printOrder)receipt.printing=result.printing;ctx.notify(result.printing.message);await ctx.refresh(true);}catch(e){ctx.notify(e.message,'error');}finally{working=false;ctx.refreshView();}return;}if(b.dataset.ticketTime){const s=shows().find(s=>s.id===b.dataset.ticketTime);if(s){chosen[s.movieId||s.title]=s.id;ctx.$('#ticketGrid').innerHTML=gridHTML();}return;}if(b.id==='ticketFinish'){finish();return;}if(pending)return;if(b.id==='ticketNew'){receipt=null;ctx.refreshView();return;}if(b.id==='ticketClear'){cart=[];updateCart();return;}const id=b.dataset.ticketAdd||b.dataset.ticketPlus||b.dataset.ticketMinus||b.dataset.ticketRemove;if(!id)return;const s=ctx.list('shows').find(s=>s.id===id),row=cart.find(r=>r.item===id);if(b.dataset.ticketRemove){cart=cart.filter(r=>r.item!==id);}else if(b.dataset.ticketMinus){if(row.quantity>1)row.quantity--;else cart=cart.filter(r=>r.item!==id);}else{const n=b.dataset.ticketAdd?Number(document.querySelector('[data-ticket-addqty="'+id+'"]').value):1;if(!Number.isInteger(n)||n<1)return ctx.notify('Introduce una cantidad entera mayor que cero.');if(!s||n+(row?.quantity||0)>(ctx.model.state.availability[id]||0))return ctx.notify('No hay suficientes boletos disponibles.');if(row)row.quantity+=n;else cart.push({item:id,title:s.title,date:s.date,time:s.time,room:s.room,quantity:n,unitPrice:s.price,seatsPerTicket:s.seatsPerTicket});}ctx.$('#ticketGrid').innerHTML=gridHTML();updateCart();});
ctx.$('#root').addEventListener('change',e=>{if(e.target.id==='ticketDate'){date=e.target.value;chosen={};ctx.$('#ticketGrid').innerHTML=gridHTML();}if(e.target.dataset.ticketQty&&!pending){const row=cart.find(r=>r.item===e.target.dataset.ticketQty),n=Number(e.target.value);if(!Number.isInteger(n)||n<1||n>2000){e.target.value=row.quantity;return ctx.notify('Cantidad inválida.');}row.quantity=n;updateCart();}});
ctx.$('#root').addEventListener('input',e=>{if(e.target.id==='ticketSearch'){query=e.target.value;ctx.$('#ticketGrid').innerHTML=gridHTML();}if(e.target.id==='ticketReceived')change();});
if(ctx.model?.user.role==='ticketing'&&ctx.page==='pos')ctx.refreshView();
const originalRender=controller.render;
controller.render=()=> (ctx.cashClosed()?ctx.openingPanel():'')+originalRender();
return controller;
}
