"""Printable document adapter; escapes all external text."""
from html import escape
from erp.shared.domain import validation as cinema

def report(run,employee=None):
    cinema.check(run.get('calculationVersion')==3 or run['status']=='Validada','Este borrador usa el cálculo anterior. Configura el descanso semanal y vuelve a calcular antes de imprimir.')
    lines=[l for l in run['lines'] if not employee or l['employee']==employee]
    cinema.check(bool(lines),'Empleado no incluido en esta planilla.')
    e=lambda x:escape(str(x));money=lambda x:f'Bs {x:,.2f}'
    blocks=[]
    for l in lines:
        extras=''.join(f'<tr><td>{e(x["date"])}</td><td>{e(('Día extra · ' if x.get('extraType')=='day' else 'Función especial · ')+x["reason"])}</td><td>{money(x["amount"])}</td></tr>' for x in l['extras'])
        late_detail=''.join(f'<tr><td>{e(x["date"])}</td><td>{e(x["entry"])} · {x["minutes"]} min de atraso</td><td>{"Día completo" if x["wholeDay"] else str(x["hours"])+" horas"}</td><td>{money(x["amount"])}</td></tr>' for x in l.get('lateRows',[]))
        blocks.append(f'<section><h2>{e(l["name"])}</h2><p>{e(l["role"])} · Código {e(l["code"])} · {e(run["month"])}</p><div class="total"><p>Sueldo mensual de referencia: <b>{money(l["base"])}</b></p><p>Días laborables cubiertos: {l.get('workedDays',l['days'])} / {l.get('expectedDays','—')}</p><p>Sueldo devengado: <b>{money(l.get('earnedBase',l['base']))}</b></p><p>Descuento por atrasos: <b>{money(l.get('lateDeduction',0))}</b></p><p>Extras: <b>{money(l["extraTotal"])}</b></p><h2>Total calculado: {money(l["total"])}</h2></div><table><tr><th>Fecha</th><th>Concepto</th><th>Extra</th></tr>{extras or "<tr><td colspan=3>Sin extras</td></tr>"}</table><h3>Detalle de atrasos</h3><table><tr><th>Fecha</th><th>Entrada / atraso</th><th>Descuento</th><th>BOB</th></tr>{late_detail or "<tr><td colspan=4>Sin descuentos por atraso</td></tr>"}</table><p>Asistencia registrada: {l["days"]} días · {l["hours"]} horas. Turnos nocturnos asignados al día de entrada.</p><p>Sueldo devengado = sueldo mensual × días laborables con asistencia válida / días laborables programados del mes. Los descansos no se consideran faltas. Se resta el descuento por atraso y se suman los extras. Solo se aplica el nivel más alto alcanzado por día, sin acumular los tres niveles. Valor hora = sueldo mensual / días laborables programados / horas de jornada. Sin retenciones ni recargos automáticos por horas. Los días sin marcación requieren revisión; no acreditan por sí solos una falta injustificada.</p></section>')
    return f'<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Reporte salarial {e(run["month"])}</title><style>body{{font:14px Arial;color:#142733;max-width:850px;margin:35px auto;padding:20px}}header{{border-bottom:3px solid;padding-bottom:20px}}section{{break-after:page;padding-top:20px}}section:last-child{{break-after:auto}}.total{{background:#edf3f5;padding:18px}}table{{width:100%;border-collapse:collapse}}td,th{{text-align:left;padding:12px;border-bottom:1px solid #ddd}}p{{line-height:1.6}}@media print{{button{{display:none}}@page{{size:A4;margin:15mm}}}}</style><link rel="stylesheet" href="/reports.css"><button onclick="window.print()">Imprimir / Guardar PDF</button><header><h1>UNIVERSAL · Reporte salarial</h1><p>{e(run["branch"])} · {e(run["status"])} · Folio {e(run["id"])}</p><small>Reporte interno. No acredita una transferencia ni un pago ejecutado.</small></header>{"".join(blocks)}</html>'.encode('utf-8')
