/** UI dependencies: badge, branch, empty, esc, list, menus, model, money, roles, table. Injected by app composition. */
export function createOperationsViews(ctx) {
function overview(){
 const sales=ctx.list('sales').filter(s=>s.day===ctx.model.today),total=sales.reduce((n,s)=>n+s.total,0),candy=sales.filter(s=>s.area==='candy').reduce((n,s)=>n+s.total,0);
 const users=ctx.model.state.users.filter(u=>['ticketing','candy'].includes(u.role)&&(ctx.branch==='Todas'||u.branch===ctx.branch));
 const rows=users.map(u=>{const own=sales.filter(s=>s.user===u.id),close=ctx.list('closures').find(c=>c.user===u.id&&c.day===ctx.model.today);return `<tr><td><strong>${u.id}</strong><small>${ctx.roles[u.role]}</small></td><td>${u.branch}</td><td>${own.length}</td><td class="amount">${ctx.money(own.reduce((n,s)=>n+s.total,0))}</td><td>${ctx.badge(close?close.status:'Caja abierta')}</td></tr>`;});
 return dashboardActions()+`<div class="metrics"><article><p>VENTAS DEL DÍA</p><strong>${ctx.money(total)}</strong><small>Ventas registradas en esta sucursal</small></article><article><p>ENTRADAS EMITIDAS</p><strong>${sales.filter(s=>s.area==='ticketing').reduce((n,s)=>n+s.quantity,0)}</strong><small>Boletos cobrados en el día</small></article><article><p>VENTAS DE CANDY</p><strong>${ctx.money(candy)}</strong><small>Cobros del equipo de Candy</small></article><article class="accent"><p>CIERRES POR REVISAR</p><strong>${ctx.list('closures').filter(c=>c.status!=='Confirmado').length}</strong><small>Validación por Contabilidad</small></article></div><div class="panel"><div class="panel-head"><div><p class="eyebrow">SEGUIMIENTO EN VIVO</p><h2>Ventas por persona</h2></div><span class="badge good">${users.length} usuarios</span></div>${ctx.table(['Usuario / área','Sucursal','Ventas','Total del día','Caja'],rows)}</div><div class="two"><section class="panel"><h2>Últimas ventas</h2>${sales.slice(-6).reverse().map(s=>`<div class="activity"><span class="activity-icon">${s.area==='candy'?'C':'B'}</span><div><strong>${ctx.esc(s.label)}</strong><small>${s.user} · ${s.at.slice(11,16)}</small></div><b>${ctx.money(s.total)}</b></div>`).join('')||ctx.empty('Sin ventas hoy')}</section><section class="panel"><h2>Control de sucursales</h2>${(ctx.branch==='Todas'?ctx.model.branches:[ctx.branch]).map(b=>`<div class="branch-line"><div><strong>${b}</strong><small>${ctx.model.state.audits.filter(a=>a.branch===b&&a.status==='En curso').length} arqueos activos</small></div><b>${ctx.money(sales.filter(s=>s.branch===b).reduce((n,s)=>n+s.total,0))}</b></div>`).join('')}<p class="muted small">Las ventas confirmadas permanecen en el historial después del cierre.</p></section></div>`;
}
function dashboardActions(){const role=ctx.model.user.role;const tasks=[{page:'closures',title:'Cierres por revisar',count:ctx.list('closures').filter(c=>c.status!=='Confirmado').length},{page:'reports',title:'Reportes pendientes',count:ctx.list('reports').filter(r=>['Pendiente','Observado'].includes(r.status)).length},{page:'audits',title:'Arqueos en curso',count:ctx.list('audits').filter(a=>a.status==='En curso').length}].filter(t=>ctx.menus[role].includes(t.page));return `<div class="task-strip"><span>Tu siguiente paso</span>${tasks.map(t=>`<button data-page="${t.page}">${t.title}<b class="${t.count?'pending-number':''}">${t.count}</b> →</button>`).join('')}${role==='manager'?'<button data-page="shows">Programar funciones →</button>':''}${role==='administrator'?'<button data-page="reports">Reportar movimiento →</button>':''}</div>`;}
function history(){const labels={payroll_delete:'Registro salarial retirado',payroll_role:'Sueldo de referencia actualizado',payroll_employee:'Empleado salarial actualizado',payroll_extra:'Extra salarial registrado',payroll_extra_void:'Extra salarial anulado',payroll_calculate:'Planilla recalculada',payroll_validate:'Planilla validada',payroll_mail_update:'Destinatario salarial actualizado',payroll_import:'Biométrico importado para salarios',candy_checkout:'Venta de Candy registrada',candy_void_request:'Anulación de Candy solicitada',candy_void_review:'Anulación de Candy revisada',cash_open:'Caja abierta',cash_void:'Movimiento de efectivo anulado',cash_movement:'Movimiento de efectivo',ticket_checkout:'Venta de boletos finalizada',room_delete:'Sala retirada',movie_delete:'Película retirada',trailer_delete:'Tráiler retirado',show_delete:'Función retirada',room_save:'Sala actualizada',movie_save:'Banner actualizado',schedule:'Programación creada',show_cancel:'Función cancelada',trailer_save:'Tráiler actualizado',sell:'Venta registrada',show:'Función publicada',report:'Movimiento reportado',review:'Reporte revisado',product:'Producto creado',stock:'Movimiento de Candy',audit_start:'Arqueo iniciado',audit_save:'Conteo guardado',audit_finish:'Arqueo finalizado',close:'Caja cerrada',close_review:'Cierre verificado'};return `<section class="panel"><div class="panel-head"><h2>Trazabilidad de operaciones</h2><label class="search-field">Buscar operación<input type="search" data-filter-table="operationRecords" placeholder="Acción, usuario o fecha…"></label></div><div id="operationRecords">${ctx.table(['Fecha y hora','Usuario','Sucursal','Acción'],ctx.list('log').slice().reverse().map(l=>`<tr><td>${l.at.slice(0,19).replace('T',' ')}</td><td>${l.user}</td><td>${l.branch}</td><td>${labels[l.action]||l.action}</td></tr>`))}</div></section>`;}
return {overview,history};
}
