"""Printable document adapter; escapes all external text."""
from html import escape
from erp.shared.domain import validation as cinema
from erp.modules.ticketing.admissions import tickets

def receipt(order, *, production=False):
    e=lambda value:escape(str(value))
    rows=''.join(f'<article class="ticket"><header><small>MULTICINE</small><h1>UNIVERSAL</h1><span>{e(order["branch"])}</span></header><div class="admission">ENTRADA INDIVIDUAL · 1 PERSONA</div><h2>{e(t["title"])}</h2><div class="time">{e(t["time"])}</div><div class="date">{e(t["date"])}</div><div class="room">{e(t["room"])} <b>{e(t["format"])}</b></div><p class="price">{"Incluida en promoción 2×1" if t["included"] else f'Bs {t["unitPrice"]:.2f}'}</p>{"<p>2×1 · Dos entradas por el precio de una</p>" if t.get("seatsPerTicket")==2 else ""}<footer><strong>{e(t["code"])}</strong><p>{e(order["at"][:16].replace("T"," "))}<br>Cajero: {e(order["user"])}</p><p>Sin butaca numerada · Conserva tu entrada</p><small>{'' if production else 'DEMO · '}No es factura fiscal</small></footer></article>' for t in tickets(order))
    return f'''<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Entradas {e(order['id'])}</title><style>body{{margin:0;background:#e9edf0;font:13px Arial;color:#121820}}.toolbar{{padding:20px;text-align:center}}button{{padding:12px 20px;cursor:pointer}}.ticket{{box-sizing:border-box;width:80mm;padding:5mm 4mm;background:white;margin:20px auto;text-align:center;box-shadow:0 4px 20px #0002;break-after:page}}header small{{letter-spacing:4px}}h1{{font-size:26px;letter-spacing:2px;margin:4px 0}}header span{{font-size:12px}}.admission{{border-top:2px solid;border-bottom:1px solid;padding:12px 0;margin-top:18px;font-size:10px;letter-spacing:1px}}h2{{font-size:23px;line-height:1.2;margin:20px 0}}.time{{font-size:38px;font-weight:800}}.date{{margin:6px 0 16px;font-size:15px}}.room{{display:flex;justify-content:space-between;border:1px solid;padding:12px;font-size:17px}}.price{{font-size:21px;font-weight:bold}}footer{{border-top:1px dashed;padding-top:16px;font-size:10px;line-height:1.7}}footer strong{{font-family:monospace;font-size:11px}}@media print{{body{{background:white}}.toolbar{{display:none}}.ticket{{margin:0;box-shadow:none;width:80mm}}@page{{size:80mm 150mm;margin:0}}}}</style><link rel="stylesheet" href="/reports.css"><div class="toolbar"><button onclick="window.print()">Imprimir boletos</button><p>Vista de entradas individuales · Epson TM-T20III · 80 mm</p><p>Venta {e(order['id'])} · Total cobrado Bs {order['total']:.2f}</p></div>{rows}</html>'''.encode('utf-8')
