import { restorePendingCandy, submitCandySale } from './application.ts';
/** UI dependencies: $, badge, branch, cashClosed, esc, field, list, model, money, notify, openingPanel, page, refresh, refreshView, table. Local basket state stays inside this factory. */
export function createCandyController(ctx) {
let controller;
let owner='',group=false,creating=false,cart=[],query='',working=false,pending=null,historyDate='',historySeller='',historyStatus='all';
const storage=()=> 'candy-checkout-'+ctx.model.user.id;
const products=()=>ctx.list('products').filter(p=>p.kind==='candy');
const locked=()=>ctx.cashClosed()||ctx.list('audits').some(a=>a.kind==='candy'&&a.status==='En curso');
const total=()=>cart.reduce((n,r)=>n+Math.round(r.unitPrice*100)*r.quantity,0)/100;
function remember(){try{if(pending)sessionStorage.setItem(storage(),JSON.stringify(pending));else sessionStorage.removeItem(storage());}catch{}}
function ensure(){if(owner===ctx.model.user.id)return;owner=ctx.model.user.id;historyDate='';historySeller='';historyStatus='all';group=false;creating=false;cart=[];query='';pending=null;try{pending=restorePendingCandy(sessionStorage.getItem(storage()));if(pending){cart=pending.lines;creating=true;}}catch{}}
function matches(){const q=query.trim().toLocaleLowerCase();return products().filter(p=>!q||p.code.toLocaleLowerCase().includes(q)||p.name.toLocaleLowerCase().includes(q));}
function productRows(){return matches().map(p=>`<button type="button" class="candy-product" data-candy-add="${p.id}" ${locked()||pending||(p.available===false||p.stock<=0)?'disabled':''}><span><small>${ctx.esc(p.code)}</small><strong>${ctx.esc(p.name)}</strong><small>${p.stock===undefined?(p.available?'Disponible':'Agotado'):p.stock+' '+ctx.esc(p.unit)+' disponibles'}</small></span><b>${ctx.money(p.price)} ＋</b></button>`).join('')||'<p class="muted">No hay productos con ese código o nombre.</p>';}
function basket(){return `<div class="panel-head"><h2>Venta en preparación</h2><span class="badge">${cart.reduce((n,r)=>n+r.quantity,0)} unidades</span></div>${pending?'<div class="banner warning">Confirmación pendiente. Reintenta para recuperar esta venta sin duplicarla.</div>':''}${cart.map(r=>`<article class="cart-line"><strong>${ctx.esc(r.name)}</strong><small>${ctx.esc(r.code)} · Precio unitario: ${ctx.money(r.unitPrice)}</small><div class="cart-controls"><label>Cantidad<input type="number" data-candy-qty="${r.item}" min="1" max="10000" step="1" value="${r.quantity}" ${pending?'disabled':''}></label><b>${ctx.money(r.unitPrice*r.quantity)}</b><button type="button" data-candy-remove="${r.item}" ${pending?'disabled':''} aria-label="Quitar ${ctx.esc(r.name)}">×</button></div></article>`).join('')||'<p class="muted">Busca un producto y agrégalo a la lista.</p>'}<div class="checkout-total"><span>Total a cobrar</span><strong>${ctx.money(total())}</strong></div><button class="primary candy-finish" data-candy-finish="yes" ${working||(!pending&&(!cart.length||locked()))?'disabled':''}>${working?'Registrando…':pending?'Reintentar cierre de venta':'Cerrar venta →'}</button><p class="muted small">El precio lo define Contabilidad. El inventario se descuenta al registrar la venta.</p>`;}
function history(){
 const orders=(ctx.model.state.candyOrders||[]).filter(o=>o.branch===ctx.branch&&(group||o.user===ctx.model.user.id)).slice().reverse();
 const visible=orders.filter(o=>{const req=(ctx.model.state.candyRequests||[]).filter(r=>r.order===o.id).at(-1);return (!historyDate||o.at.slice(0,10)===historyDate)&&(!group||!historySeller||o.user===historySeller)&&(historyStatus==='all'||(historyStatus==='void'?o.voided:historyStatus==='pending'?!o.voided&&req?.status==='Pendiente':!o.voided&&req?.status!=='Pendiente'));});
 return `<section class="panel candy-history"><div class="panel-head"><div><p class="eyebrow">${group?'EQUIPO DE LA SUCURSAL':'MIS VENTAS'}</p><h2>Historial de ventas</h2></div><div class="tabs"><button data-candy-view="mine" class="${group?'':'active'}" aria-pressed="${!group}">Mis ventas</button><button data-candy-view="all" class="${group?'active':''}" aria-pressed="${group}">Todo el equipo</button></div></div><div class="list-filters candy-history-filters"><label>Fecha de venta<input id="candyHistoryDate" type="date" value="${ctx.esc(historyDate)}"></label>${group?`<label>Vendedor<select id="candyHistorySeller"><option value="">Todos los vendedores</option>${[...new Set(orders.map(o=>o.user))].map(user=>`<option value="${ctx.esc(user)}" ${historySeller===user?'selected':''}>${ctx.esc(user)}</option>`).join('')}</select></label>`:''}<label>Estado<select id="candyHistoryStatus"><option value="all">Todos los estados</option><option value="registered" ${historyStatus==='registered'?'selected':''}>Registrada</option><option value="pending" ${historyStatus==='pending'?'selected':''}>Anulación pendiente</option><option value="void" ${historyStatus==='void'?'selected':''}>Anulada</option></select></label><button data-candy-reset-filters="yes">Limpiar filtros</button></div><div class="history-summary"><span>${visible.length} ventas ${group?'del equipo':'individuales'}</span><span>Total vigente en la lista <strong>${ctx.money(visible.filter(o=>!o.voided).reduce((n,o)=>n+o.total,0))}</strong></span></div>${visible.length?ctx.table(['Fecha / recibo','Vendedor / productos','Total','Estado','Acciones'],visible.map(o=>{const request=(ctx.model.state.candyRequests||[]).filter(r=>r.order===o.id).at(-1);return `<tr><td>${ctx.esc(o.at.slice(0,16).replace('T',' '))}<small class="receipt-code">${ctx.esc(o.id)}</small></td><td>${ctx.esc(o.user)}<details class="sale-lines"><summary>${o.lines.reduce((n,l)=>n+l.quantity,0)} unidades · ver productos</summary><small>${o.lines.map(l=>`${l.quantity} × ${ctx.esc(l.name)}`).join('<br>')}</small></details></td><td class="sale-value">${ctx.money(o.total)}</td><td>${ctx.badge(o.voided?'Anulada':request?.status==='Pendiente'?'Anulación pendiente':'Registrada')}${request?`<small>Solicitud: ${ctx.esc(request.status)}${request.note?' · '+ctx.esc(request.note):''}</small>`:''}</td><td><div class="receipt-actions"><a class="button" target="_blank" rel="noopener" href="/api/candy-receipt/${o.id}">Imprimir recibo ↗</a>${o.user===ctx.model.user.id&&!o.voided&&request?.status!=='Pendiente'?`<button class="danger" data-candy-void="${o.id}">Solicitar anulación</button>`:''}</div></td></tr>`;})):'<div class="empty"><h3>No hay ventas para mostrar</h3><p>Prueba otra fecha o limpia los filtros.</p></div>'}</section>`;
}
function dockHTML(){return `<div class="pos-mobile-dock" id="candyDock"><div><small>${cart.reduce((n,r)=>n+r.quantity,0)} unidades en tu venta</small><strong>${ctx.money(total())}</strong></div><button class="primary" data-candy-cart="yes">Ver venta ↑</button></div>`;}
function render(){ensure();return `${ctx.cashClosed()?ctx.openingPanel():''}<div class="pos-section-heading"><div><p class="eyebrow">${creating?'NUEVA VENTA':'CANDY BAR'}</p><h2>${creating?'Prepara el siguiente pedido':'Tus ventas, a mano'}</h2><p class="muted">${creating?'Busca, añade y confirma las cantidades.':'Consulta los recibos y empieza una nueva venta.'}</p></div>${creating?`<button data-candy-cancel="yes" ${pending?'disabled':''}>← Volver al historial</button>`:`<button class="primary" data-candy-new="yes" ${locked()?'disabled':''}>＋ Nueva venta</button>`}</div>${locked()?`<div class="banner warning">${ctx.cashClosed()?'Abre una caja para registrar nuevas ventas.':'Arqueo de Candy bar en curso. Las ventas se habilitarán al finalizar.'}</div>`:''}${creating?`<div id="candyProgress">${window.UniversalUI.steps(['Productos','Cantidades','Confirmación'],cart.length?1:0)}</div><div class="ticket-layout candy-layout"><section class="panel candy-search-panel"><div class="candy-search-heading"><label>Buscar por código o nombre<input id="candySearch" type="search" value="${ctx.esc(query)}" placeholder="Ej. XXX1 o Combo Universal" autocomplete="off" ${pending?'disabled':''}></label><small>Escribe un código y pulsa Enter para agregar una unidad.</small></div><div id="candyProducts" class="candy-products">${productRows()}</div></section><section class="panel ticket-cart" id="candyBasket" tabindex="-1" aria-label="Resumen de venta">${basket()}</section></div>${dockHTML()}`:history()}`;}
function requests(){if(!['accounting','manager'].includes(ctx.model.user.role))return '';const rows=(ctx.model.state.candyRequests||[]).filter(r=>ctx.branch==='Todas'||r.branch===ctx.branch).slice().reverse();return `<section class="panel"><h2>Solicitudes de anulación · Candy bar</h2><p class="muted small">Aprobar retira el importe de las ventas y recalcula el cierre. Comprueba la devolución del cobro y si los productos deben regresar al inventario.</p>${ctx.table(['Solicitud','Venta / motivo','Estado / resolución'],rows.map(r=>{const o=(ctx.model.state.candyOrders||[]).find(o=>o.id===r.order);return `<tr><td>${ctx.esc(r.at.slice(0,16).replace('T',' '))}<small>${ctx.esc(r.user)} · ${ctx.esc(r.branch)}</small></td><td>${o?ctx.money(o.total):'—'}<small>${ctx.esc(r.reason)}</small><a href="/api/candy-receipt/${ctx.esc(r.order)}" target="_blank">Ver recibo ↗</a></td><td>${ctx.badge(r.status)}${r.note?`<small>${ctx.esc(r.note)} · ${ctx.esc(r.reviewer)}</small>`:''}${ctx.model.user.role==='accounting'&&r.status==='Pendiente'?`<form data-action="candy_void_review" data-id="${r.id}" data-branch="${ctx.esc(r.branch)}" class="compact"><label>Decisión<select name="status"><option value="">Selecciona…</option><option>Aprobado</option><option>Rechazado</option></select></label><label>¿Regresan los productos al inventario?<select name="restoreStock"><option value="">Selecciona…</option><option value="yes">Sí, productos recuperados</option><option value="no">No, productos entregados / consumidos</option></select></label><label>Motivo y devolución del cobro<input name="note" maxlength="300" required></label><button>Guardar resolución</button></form>`:''}</td></tr>`;}))}</section>`;}
function drawBasket(){if(ctx.$('#candyProgress'))ctx.$('#candyProgress').innerHTML=window.UniversalUI.steps(['Productos','Cantidades','Confirmación'],cart.length?1:0);if(ctx.$('#candyDock'))ctx.$('#candyDock').outerHTML=dockHTML();if(ctx.$('#candyBasket'))ctx.$('#candyBasket').innerHTML=basket();if(ctx.$('#candyProducts'))ctx.$('#candyProducts').innerHTML=productRows();}
function add(id){if(pending||working||locked())return;const p=products().find(p=>p.id===id);if(!p)return;const r=cart.find(r=>r.item===id);if(p.available===false||(r?.quantity||0)+1>(p.stock??10000)){ctx.notify('No hay más existencias disponibles.');return;}if(r)r.quantity++;else cart.push({item:p.id,code:p.code,name:p.name,quantity:1,unitPrice:p.price});drawBasket();}
async function finish(){if(working)return;if(!pending){if(locked()||!cart.length)return;pending={action:'candy_checkout',branch: ctx.branch,requestId:crypto.randomUUID(),lines:cart.map(r=>({...r}))};remember();}working=true;drawBasket();try{const response=await submitCandySale(ctx.transport,pending);const result=response.body;if(!response.ok){if(response.status===400){pending=null;remember();}throw new Error(result.error||'No se pudo confirmar la venta.');}pending=null;remember();cart=[];creating=false;query='';await ctx.refresh(true);ctx.notify('Venta registrada. Ya puedes imprimir el recibo desde el historial.');}catch(e){ctx.notify(e.message,'error');if(!pending){await ctx.refresh();cart=cart.map(r=>({...r,unitPrice:products().find(p=>p.id===r.item)?.price??r.unitPrice}));}}finally{working=false;drawBasket();}}
ctx.$('#root').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.candyCart){ctx.$('#candyBasket')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});ctx.$('#candyBasket')?.focus({preventScroll:true});return;}if(b.dataset.candyResetFilters){historyDate='';historySeller='';historyStatus='all';ctx.refreshView();return;}if(b.dataset.candyNew){creating=true;ctx.refreshView();ctx.$('#candySearch')?.focus();}if(b.dataset.candyCancel){if(cart.length&&!confirm('¿Descartar la venta en preparación?'))return;creating=false;cart=[];query='';ctx.refreshView();}if(b.dataset.candyView){group=b.dataset.candyView==='all';historySeller='';ctx.refreshView();}if(b.dataset.candyAdd)add(b.dataset.candyAdd);if(b.dataset.candyRemove&&!pending){cart=cart.filter(r=>r.item!==b.dataset.candyRemove);drawBasket();}if(b.dataset.candyFinish)finish();if(b.dataset.candyVoid){const d=document.createElement('dialog');d.className='cash-dialog';d.innerHTML=`<h2>Solicitar anulación de venta</h2><p class="muted">Contabilidad revisará el error. La venta seguirá vigente hasta que se apruebe su anulación.</p><form data-action="candy_void_request" data-id="${ctx.esc(b.dataset.candyVoid)}" data-branch="${ctx.esc(ctx.branch)}">${ctx.field('Explica el error','reason','text','','maxlength="300"')}<div class="actions"><button type="button" data-cash-dismiss="yes">Cancelar</button><button class="primary">Enviar solicitud</button></div></form>`;ctx.$('#root').append(d);d.showModal();d.addEventListener('close',()=>d.remove());}});
ctx.$('#root').addEventListener('input',e=>{if(e.target.id==='candySearch'){query=e.target.value;ctx.$('#candyProducts').innerHTML=productRows();}});
ctx.$('#root').addEventListener('change',e=>{if(e.target.id==='candyHistoryDate'){historyDate=e.target.value;ctx.refreshView();}if(e.target.id==='candyHistorySeller'){historySeller=e.target.value;ctx.refreshView();}if(e.target.id==='candyHistoryStatus'){historyStatus=e.target.value;ctx.refreshView();}if(e.target.dataset.candyQty&&!pending){const r=cart.find(r=>r.item===e.target.dataset.candyQty);const p=products().find(p=>p.id===r?.item),n=Number(e.target.value);if(r&&Number.isInteger(n)&&n>0&&n<=Math.min(10000,p?.stock??(p?.available?10000:0)))r.quantity=n;else ctx.notify('Ingresa una cantidad entera dentro de las existencias disponibles.');drawBasket();}});
ctx.$('#root').addEventListener('keydown',e=>{if(e.target.id==='candySearch'&&e.key==='Enter'){e.preventDefault();const p=products().find(p=>p.code.toLocaleLowerCase()===query.trim().toLocaleLowerCase())||(matches().length===1?matches()[0]:null);if(p)add(p.id);else ctx.notify('Selecciona uno de los productos encontrados.');}});
controller={render,requests,editing:()=>ctx.model?.user.role==='candy'&&ctx.page==='pos'&&creating,reset:()=>{owner='';group=false;creating=false;cart=[];query='';pending=null;}};
return controller;
}
