/** UI dependencies: $, badge, branch, esc, field, list, model, money, roles, table. Injected by app composition. */
export function createCashViews(ctx) {
function currentCash(){return (ctx.model.state.cashOpenings||[]).slice().reverse().find(o=>o.user===ctx.model.user.id&&!o.closed);}
function cashClosed(){return !currentCash()&&ctx.list('closures').some(c=>c.user===ctx.model.user.id);}
function openingPanel(){return cashClosed()?'<div class="banner">Caja cerrada. <button type="button" data-open-cash="yes">Abrir nueva caja</button></div>':'';}
function showOpeningDialog(){if(!cashClosed()||ctx.$('#openingDialog'))return;const d=document.createElement('dialog');d.id='openingDialog';d.className='cash-dialog';d.innerHTML=`<p class="eyebrow">COMIENZA TU JORNADA</p><h2>Apertura de caja</h2><p class="muted">Registra la apertura para habilitar las ventas. El fondo inicial es opcional.</p><form data-action="cash_open"><label>Fondo inicial · BOB (opcional)<input name="amount" type="number" min="0" max="100000" step="0.01" placeholder="0,00"></label><div class="actions"><button type="button" data-cash-dismiss="yes">Más tarde</button><button class="primary">Abrir caja →</button></div></form>`;ctx.$('#root').append(d);d.showModal();d.addEventListener('close',()=>d.remove());}
function openCashDialog(direction,id='',scope=ctx.branch){
 ctx.$('#cashDialog')?.remove();const cancel=direction==='void',title=cancel?'Anular movimiento':direction==='in'?'Registrar ingreso':'Registrar egreso';
 const dialog=document.createElement('dialog');dialog.id='cashDialog';dialog.className='cash-dialog';
 dialog.innerHTML=`<div class="panel-head"><div><p class="eyebrow">CONTROL DE EFECTIVO</p><h2>${title}</h2></div><button type="button" data-cash-dismiss="yes" aria-label="Cerrar ventana">✕</button></div><p class="muted small">${cancel?'El registro se conservará como anulado y dejará de afectar el saldo. Si tiene cierre, quedará pendiente de nueva revisión.':'Completa los datos para registrar el movimiento en tu caja.'}</p><form data-action="${cancel?'cash_void':'cash_movement'}" data-id="${ctx.esc(id)}" data-branch="${ctx.esc(scope)}"><input type="hidden" name="direction" value="${direction}">${cancel?'':ctx.field('Importe BOB','amount','number','','min="0.01" max="100000" step="0.01"')}${ctx.field(cancel?'Motivo de anulación':'Motivo','reason','text','','maxlength="300"')}${cancel?'':'<label>Referencia (opcional)<input name="reference" maxlength="100"></label>'}<div class="actions"><button type="button" data-cash-dismiss="yes">Cancelar</button><button class="primary">${cancel?'Confirmar anulación':'Guardar movimiento'}</button></div></form>`;
 ctx.$('#root').append(dialog);dialog.showModal();dialog.addEventListener('close',()=>dialog.remove());
}
function cashLedger(){
 if(!['accounting','manager','administrator'].includes(ctx.model.user.role))return '';
 const moves=(ctx.model.state.cashMovements||[]).filter(m=>ctx.branch==='Todas'||m.branch===ctx.branch).slice().reverse();
 return `<section class="panel"><h2>Ingresos y egresos de caja</h2><p class="muted small">Movimientos de Boletería y Candy bar. Los anulados se conservan para consulta y no afectan el saldo.</p>${ctx.table(['Fecha / sucursal','Cajero / área','Movimiento','Importe','Estado'],moves.map(m=>`<tr><td>${ctx.esc(m.day)}<small>${ctx.esc(m.branch)} · ${ctx.esc(m.at.slice(11,19))}</small></td><td>${ctx.esc(m.user)}<small>${ctx.esc(ctx.roles[m.area])}</small></td><td><strong>${m.direction==='in'?'Ingreso':'Egreso'}</strong><small>${ctx.esc(m.reason)}</small><small>Referencia: ${ctx.esc(m.reference)||'—'}</small></td><td>${ctx.money(m.total)}</td><td>${ctx.badge(m.voided?'Anulado':'Vigente')}${m.voided?`<small>${ctx.esc(m.voidReason)}<br>${ctx.esc(m.voidBy)} · ${ctx.esc(m.voidAt)}</small>`:ctx.model.user.role==='accounting'?`<button class="danger" data-cash-void="${ctx.esc(m.id)}" data-branch="${ctx.esc(m.branch)}">Anular</button>`:''}</td></tr>`))}</section>`;
}
function cashSummary(){
 const sales=ctx.list('sales').filter(s=>s.user===ctx.model.user.id&&(currentCash()?s.cashSession===currentCash().id:!s.cashSession&&s.day===ctx.model.today)),moves=(ctx.model.state.cashMovements||[]).filter(m=>m.user===ctx.model.user.id&&(currentCash()?m.cashSession===currentCash().id:!m.cashSession&&m.day===ctx.model.today));
 const sum=rows=>Math.round(rows.reduce((n,r)=>n+r.total,0)*100)/100;
 const salesTotal=sum(sales),incomeTotal=sum(moves.filter(m=>m.direction==='in'&&!m.voided)),expenseTotal=sum(moves.filter(m=>m.direction==='out'&&!m.voided));
 return {salesTotal,incomeTotal,expenseTotal,expected:Math.round((salesTotal+incomeTotal-expenseTotal)*100)/100,movements:moves,quantity:sales.reduce((n,s)=>n+s.quantity,0)};
}
function cashPreview(){const input=ctx.$('[data-action="close"] [name="physical"]'),out=ctx.$('#cashDifference');if(!input||!out)return;const d=Math.round((Number(input.value)-cashSummary().expected)*100)/100;out.textContent=input.value===''?'Ingresa el efectivo contado':ctx.money(d)+' · '+(d===0?'Caja cuadrada':d>0?'Sobrante':'Faltante');out.className=d!==0&&input.value!==''?'negative':'amount';}
function closures(){
 const user=ctx.model.user,seller=['candy','ticketing'].includes(user.role),own=cashClosed()?ctx.list('closures').slice().reverse().find(c=>c.user===user.id):null;let form='';
 if(seller){const d=own?.detail||cashSummary();form=`<section class="panel cash-header"><div class="panel-head"><div><p class="eyebrow">CIERRE DIARIO · ${ctx.esc(ctx.roles[user.role])}</p><h2>1. Revisa tu caja</h2></div>${ctx.badge(own?own.status:'Caja abierta')}</div><div class="cash-metrics"><article><small>Ventas del día</small><strong>${ctx.money(d.salesTotal)}</strong><span>${d.quantity} ${user.role==='ticketing'?'boletos cobrados':'unidades vendidas'}</span></article><article><small>Otros ingresos</small><strong>${ctx.money(d.incomeTotal)}</strong><span>Fondos y entradas adicionales</span></article><article><small>Egresos</small><strong>${ctx.money(d.expenseTotal)}</strong><span>Retiros y salidas de efectivo</span></article><article class="accent"><small>Saldo esperado</small><strong>${ctx.money(own?.expected??d.expected)}</strong><span>Ventas + ingresos − egresos</span></article></div>${own?`<p class="muted">Caja cerrada. Los importes y movimientos quedaron guardados para su revisión.</p><a class="button" target="_blank" href="/api/closing/${own.id}">Imprimir reporte de cierre ↗</a>`:`<div class="cash-buttons"><button data-cash-direction="in">＋ Registrar ingreso</button><button data-cash-direction="out">− Registrar egreso</button></div><p class="muted small">Registra aquí el fondo inicial, reposiciones o retiros. Estos movimientos modifican el efectivo esperado, sin sumarse a las ventas.</p>`}</section><section class="panel"><div class="panel-head"><h2>Movimientos de efectivo</h2><small>${ctx.esc(ctx.model.today)} · ${ctx.esc(user.id)}</small></div>${d.movements.length?ctx.table(['Hora','Movimiento / motivo','Referencia','Importe'],d.movements.map(m=>`<tr><td>${ctx.esc(m.at.slice(11,19))}</td><td><strong>${m.direction==='in'?'Ingreso':'Egreso'}</strong><small>${ctx.esc(m.reason)}${m.voided?' · ANULADO: '+ctx.esc(m.voidReason):''}</small></td><td>${ctx.esc(m.reference)||'—'}</td><td class="${m.direction==='in'?'amount':'negative'}">${m.direction==='in'?'+':'−'} ${ctx.money(m.total)}</td></tr>`)):'<p class="muted">No hay ingresos ni egresos adicionales registrados hoy.</p>'}</section>`;
 if(!own)form+=`<section class="panel"><p class="eyebrow">CONCILIACIÓN Y ENTREGA</p><h2>2. Cuenta el efectivo</h2><p class="muted">Cuenta el efectivo que entregarás. El sistema compara ese importe con el saldo esperado y conserva cualquier sobrante o faltante.</p><form data-action="close" class="form-grid">${ctx.field('Efectivo físico contado · BOB','physical','number','','min="0" step="0.01"')}<label>Observaciones<input name="note" maxlength="300" placeholder="Detalle de entrega o diferencia"></label><div class="cash-reconcile"><small>Saldo esperado</small><b>${ctx.money(cashSummary().expected)}</b><small>Diferencia = contado − esperado</small><strong id="cashDifference">Ingresa el efectivo contado</strong></div><button class="primary">3. Confirmar cierre →</button></form><p class="muted small">Al cerrar se bloquean las ventas, ingresos y egresos hasta una nueva apertura. Contabilidad verificará la entrega. Las ventas anticipadas se incluyen en el día del cobro.</p></section>`;}
 return (seller&&!currentCash()?openingPanel():'')+form+cashLedger()+`<section class="panel"><div class="panel-head"><h2>Historial de cierres</h2><label class="search-field">Buscar cierre<input type="search" data-filter-table="closingRecords" placeholder="Fecha, usuario o estado…"></label></div><div id="closingRecords">${ctx.table(['Día / usuario','Sucursal','Esperado','Físico','Diferencia','Estado / reporte'],ctx.list('closures').slice().reverse().map(c=>`<tr><td>${c.day}<small>${ctx.esc(c.user)}</small></td><td>${ctx.esc(c.branch)}</td><td>${ctx.money(c.expected)}</td><td>${ctx.money(c.physical)}</td><td class="${c.difference?'negative':'amount'}">${ctx.money(c.difference)}</td><td>${ctx.badge(c.status)}<p><a target="_blank" href="/api/closing/${c.id}">Ver / imprimir reporte ↗</a></p>${c.note?`<small>${ctx.esc(c.note)}</small>`:''}${user.role==='accounting'&&c.status!=='Confirmado'?`<form data-action="close_review" data-id="${c.id}" data-branch="${c.branch}" class="compact">${ctx.field('Físico verificado','physical','number',c.physical,'min="0" step="0.01"')}<input name="note" placeholder="Detalle de verificación" required><button>Verificar cierre</button></form>`:''}</td></tr>`))}</div><p class="muted small">Contabilidad confirma únicamente si la diferencia es cero. Las diferencias quedan observadas.</p></section>`;
}
return {cashClosed,openingPanel,showOpeningDialog,openCashDialog,cashPreview,closures};
}
